version: '3.5'
services:
  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  zabbix-web:
    container_name: zabbix-web
    hostname: zabbix-web
    image: zabbix/zabbix-web-apache-mysql:alpine-5.0-latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  zabbix-agent:
    container_name: zabbix-agent
    hostname: zabbix-agent
    image: zabbix/zabbix-agent:alpine-5.0-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro