services:
  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:7.0-alpine-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DB_SERVER_HOST=mariadb-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mariadb-server

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:7.0-alpine-latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mariadb-server
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    depends_on:
      - mariadb-server
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    hostname: zabbix-agent
    image: zabbix/zabbix-agent:7.0-alpine-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_ACTIVE_ALLOW=false
    depends_on:
      - zabbix-server
