version: '3.5'
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-5.0.30
    ports:
      - 10051:10051
    environment:
      DB_SERVER_HOST: <Database Name/IP>
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_CACHESIZE: 32M
    restart: always
    
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0.30
    ports:
      - 8080:8080
    environment:
      ZBX_SERVER_HOST: <Server Name/IP>
      DB_SERVER_HOST: <Database Name/IP>
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    restart: always
    depends_on:
      - zabbix-server
      
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-5.0.30
    ports:
      - "10050:10050"
    environment:
      ZBX_PASSIVESERVERS: <Server Name/IP>
      ZBX_ACTIVESERVERS: <Server Name/IP>
      ZBX_HOSTNAME: <Agent Hostname>
      
zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-5.0.30
  ports:
   - "162:1162/udp"
